### ISSUE TITLE
openj9-systemtest build should not require JVM_VERSION to be set

### ISSUE THREAD

**Issue by lumpfish** [eclipse/openj9-systemtest#27] opened 2018-06-15 10:42 UTC
This check has recently been added to openj9.build/build.xml:
```
	<condition property="isOpenJ9" value="true">
		<contains string="${JVM_VERSION}" substring="openj9"/>
	</condition>
```

This property is used as a guard to not build on platforms where the openj9 features are not available.

However, if a user follows the build instructions for the repository, JVM_VERSION will not be set (I assume this is added by the Jenkins build pipelines?)
The JVM version should be able to be determined from the system properties of the java being used for the build.
Note that there are two types of Java which could be used for building these tests - openjdk-openj9 releases and IBM Java releases, so a suitable property (or properties) should be interrogated to provide the information.

**Comment by Mesbah-Alam** [comment] 2019-01-21 18:56
Hi Simon, 

Just wondering, which file were you referring to where you saw the condition property? 

```
<condition property="isOpenJ9" value="true">
		<contains string="${JVM_VERSION}" substring="openj9"/>
	</condition>
``` 

The above condition is now only used in systemtest/playlist.xml : https://github.com/AdoptOpenJDK/openjdk-tests/blob/652add09c02215b89c697e475d933aa53a5d2162/systemtest/build.xml#L150

This playlist can only be used (be it in build or local run) in conjunction with TetConfig, in which case JVM_VERSION is automatically set. 

If systemtest/playlist.xml is the only file you were referring to, then we should be able to close this issue at the moment. 

@lumpfish

**Comment by lumpfish** [comment] 2019-01-22 14:16
@Mesbah-Alam , I believe this issue was fixed by https://github.com/eclipse/openj9-systemtest/pull/45, so I think it can now be closed.

**Closed** 2019-01-22 15:27 UTC

**Comment by smlambert** [comment] 2019-01-22 17:35
@Mesbah-Alam to save having to come back and manually close issues, git keyword "fixes issueNume" or ["closes issueNum" (see doc)](https://help.github.com/articles/closing-issues-using-keywords/) is a good technique to use in your PRs, then when the PR is merged, the issue is automatically closed.  Please start taking advantage of it where appropriate :)
